
namespace Touhou.Networking;
public enum PacketType : byte {
    LatencyCorrection,
    Connection,
    ConnectionResponse,
    TimeRequest,
    TimeResponse,
    SyncFinished,
    ChangedCharacter,
    SelectedCharacter,
    DeselectedCharacter,
    MatchReady,
    MatchStarted,
    VelocityChanged,
    AttackPressed,
    AttackReleased,
    BombPressed,
    SpentPower,
    EffectApplied,
    EffectCancelled,
    Grazed,
    Hit,
    Knockbacked,
    Death,
    DeathConfirmation,
    Rematch,
    UpdateProjectile,
    DestroyProjectile,
}